### ISSUE TITLE
Get ready for open-source

### ISSUE THREAD

**Issue by Vinetos** [DemonDxv/Xan-Anticheat#1]
# Your project isn't ready for open-source.
Consider the following :
- Don't commit and push the `out/` folder. 
> Binaries shouldn't be committed as it isn't source code.
- Don't commit and push `libs` folder. 
> You should use a dependency manager as Gradle or Maven. OR use git lfs to push binaries.
- Use a better `.gitignore`. 
> It prevents bad files to be pushed. You can generate one here : https://www.toptal.com/developers/gitignore
- Add `LICENSE`. 
> Without License, I can reuse this plugin and sell it as it was mine.

**Comment by DemonDxv** [comment]
Out folder is now gone.

Libs folder is for anyone who wants/needs the libs for the anticheat to work on it.

.gitignore is fine.

License is not required as all I require is for you to credit me on my work.

**Comment by Vinetos** [comment]
> Libs folder is for anyone who wants/needs the libs for the anticheat to work on it.  

It is better to use a dependencies manager like Gradle or Maven. It will be easier to compile and tests the project everywhere 😉

**Comment by Numzskull** [comment]
I'm not going to setup a license for him, as that isn't for me to do, but I have fixed most these issues, and requests in pull request #2 .
Please mention if there is anything else that might need to be changed

**Comment by Vinetos** [comment]
LICENSE isn't really useful because of the author's right
But it still a good idea to create and use one
